### ISSUE TITLE
Fixed IPD in software?

### ISSUE THREAD

**Issue by greenalden** [LordOfDragons/democap#2]
Sorry to post a new issue alongside the one I just posted. I noticed that the world scale seemed a bit off especially when I moved my head. My assumption is it is one of 2 or possibly both of these things, first, the headset tracking could be offset but I find this unlikely. Secondly, I believe that the IDP may be hardcoded in software. On my Valve Index, I had my IPD set the to lowest setting and I believe that the software may not be accounting for the user's IPD.

**Comment by greenalden** [comment]
doing a proper actor measurement improves it but it still feels off.

**Comment by LordOfDragons** [comment]
This is actually a feature not a bug. To allow capturing various characters with non-human proportions the camera is placed where the eyes of the character are not where your HMD is. This gives a difference. You can disable this behavior by [not setting a bone for the camera bone](https://developer.dragondreams.ch/wiki/lib/exe/fetch.php/democap:dialogcharacterconfiguration.png). This way you will though most probably clip through parts of the character at times.

The IPD is not hardcoded in software. The OpenXR environment (SteamVR for example) reports the 2 eye matrices to use. Hence the IPD is baked into these matrices. If they are incorrect then the OpenXR environment needs recalibration. With SteamVR this can happen if lighthouses moved since the last time you used them.

**Comment by greenalden** [comment]
That is actually really cool, though it was a bit disorienting at first.
